# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentSecret < Formula
  desc "A secure local secret vault for developers"
  homepage "https://github.com/onurkerem/agent-secret"
  version "1.0.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/onurkerem/agent-secret/releases/download/v1.0.0/agent-secret_1.0.0_darwin_amd64.tar.gz"
      sha256 "91db2d965e6548c4366ca86ab31fbc573f7f696540b370afe6bbc8ff1c0f1e83"

      def install
        bin.install "agent-secret"
      end
    end
    on_arm do
      url "https://github.com/onurkerem/agent-secret/releases/download/v1.0.0/agent-secret_1.0.0_darwin_arm64.tar.gz"
      sha256 "670dd0b4728cad6b4b5abf16a284f7e849e2b80e0d548c970d6c59c95ca78b84"

      def install
        bin.install "agent-secret"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/onurkerem/agent-secret/releases/download/v1.0.0/agent-secret_1.0.0_linux_amd64.tar.gz"
        sha256 "8afe1fe59b4fb9d5b7c070dc5753dde52f0adc416ea972448819097c14344cb4"

        def install
          bin.install "agent-secret"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/onurkerem/agent-secret/releases/download/v1.0.0/agent-secret_1.0.0_linux_arm64.tar.gz"
        sha256 "41673da8c7a9926011edb6a4efc7c433680a01360a2693b4d7a850be958c9710"

        def install
          bin.install "agent-secret"
        end
      end
    end
  end

  test do
    system "#{bin}/agent-secret --version"
  end
end
