# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentSecret < Formula
  desc "A secure local secret vault for developers"
  homepage "https://github.com/onurkerem/agent-secret"
  version "1.2.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/onurkerem/agent-secret/releases/download/v1.2.0/agent-secret_1.2.0_darwin_amd64.tar.gz"
      sha256 "0e2085b25aacf11771df981eba6ef418ab003c5a91174e96983785dcadc11c27"

      def install
        bin.install "agent-secret"
      end
    end
    on_arm do
      url "https://github.com/onurkerem/agent-secret/releases/download/v1.2.0/agent-secret_1.2.0_darwin_arm64.tar.gz"
      sha256 "782d1eb408bcee279a62a62c45f8aca8633a232944dbc4f24e2ec1f0737a0f56"

      def install
        bin.install "agent-secret"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/onurkerem/agent-secret/releases/download/v1.2.0/agent-secret_1.2.0_linux_amd64.tar.gz"
        sha256 "a1d7f592fb1c81150c66adf2708e3452f7f0ad6c10da3e5c7ec0b266f8f2058b"

        def install
          bin.install "agent-secret"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/onurkerem/agent-secret/releases/download/v1.2.0/agent-secret_1.2.0_linux_arm64.tar.gz"
        sha256 "f04f36f5651fb30d4c0a7bc01e9188162b434f0982d7daf5f528d25aaece82f1"

        def install
          bin.install "agent-secret"
        end
      end
    end
  end

  test do
    system "#{bin}/agent-secret --version"
  end
end
