# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentSecret < Formula
  desc "A secure local secret vault for developers"
  homepage "https://github.com/onurkerem/agent-secret"
  version "1.1.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/onurkerem/agent-secret/releases/download/v1.1.0/agent-secret_1.1.0_darwin_amd64.tar.gz"
      sha256 "5cd5710bae42576fa0f1f5620c1a3917092218df5ff5c5d3cfdf627715c6e1a2"

      def install
        bin.install "agent-secret"
      end
    end
    on_arm do
      url "https://github.com/onurkerem/agent-secret/releases/download/v1.1.0/agent-secret_1.1.0_darwin_arm64.tar.gz"
      sha256 "de7ffdf525a336f6a5bff4bc70b1a8aae41aec24d3cce8106f360419895fd0fe"

      def install
        bin.install "agent-secret"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/onurkerem/agent-secret/releases/download/v1.1.0/agent-secret_1.1.0_linux_amd64.tar.gz"
        sha256 "290eace9bd59e173f35f6f4656c6561b2f5704584f4c589215294734d4da377a"

        def install
          bin.install "agent-secret"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/onurkerem/agent-secret/releases/download/v1.1.0/agent-secret_1.1.0_linux_arm64.tar.gz"
        sha256 "354380bbebf7f653e5c4164814b8907d25964247ec312364f68825a3316d62bf"

        def install
          bin.install "agent-secret"
        end
      end
    end
  end

  test do
    system "#{bin}/agent-secret --version"
  end
end
